version: "3.9"

services:

  mysql:
    container_name: mysql_c
#    volumes:
#      - mysql_vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: profesor
    build:
      context: ./mysql
    image: localhost:5000/mysql_img

  tomcat:
    container_name: tomcat_c
    build:
      context: ./tomcat
    image: localhost:5000/tomcat_img
    depends_on:
      - mysql

  nginx:
    container_name: nginx_c
    build:
      context: ./nginx
    image: localhost:5000/nginx_img
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mysql
      - tomcat

#volumes:
#  mysql_vol:
